{
  "entity": {
    "location": {
      "namespaceTitle": "Fuse",
      "namespaceUri": "fuse",
      "packageName": "Fuse.Nodes",
      "packageVersion": "1.8.0-rc2"
    },
    "parameters": [
      {
        "name": "e",
        "href": "uno/exception",
        "title": "Exception",
        "fullyQualifiedTitle": "Uno.Exception"
      },
      {
        "name": "propagate",
        "href": "uno/bool",
        "title": "bool",
        "fullyQualifiedTitle": "bool"
      }
    ],
    "id": {
      "id": "fuse/appbase/onunhandledexception_b48b8df2",
      "parentId": "fuse/appbase",
      "type": "Method",
      "modifiers": [
        "public"
      ]
    },
    "uri": {
      "idUri": "fuse/appbase/onunhandledexception_b48b8df2",
      "href": "fuse/appbase/onunhandledexception_b48b8df2"
    },
    "titles": {
      "pageTitle": "AppBase.OnUnhandledException Method (Exception, bool)",
      "navigationTitle": "OnUnhandledException Method (Exception, bool)",
      "fullTitle": "Fuse.AppBase.OnUnhandledException",
      "indexTitle": "OnUnhandledException(Exception, bool)",
      "fullyQualifiedIndexTitle": "Fuse.AppBase.OnUnhandledException(Uno.Exception, bool)"
    },
    "syntax": {
      "uno": "public voidOnUnhandledException(Uno.Exception e, bool propagate = true) {}"
    },
    "comment": {
      "brief": "Notfies the @App about an unhandled exception within a subsystem of the app.\nIf implementing a subsystems (such as separate threads) where exceptions can be\nthrown out of the app, you can catch such otherwise unhandled exceptions and report them\nto this method, to allow users to use the @UnhandledException event to deal with\nsuch exceptions instead of crashing the @App.",
      "full": "Notfies the @App about an unhandled exception within a subsystem of the app.\nIf implementing a subsystems (such as separate threads) where exceptions can be\nthrown out of the app, you can catch such otherwise unhandled exceptions and report them\nto this method, to allow users to use the @UnhandledException event to deal with\nsuch exceptions instead of crashing the @App.\n\n@hide"
    }
  },
  "tableOfContents": {}
}